spring.application.name=demo
# Disable devtools automatic restart when running in a production environment
spring.devtools.restart.enabled=true

# Set the directory for watching file changes (default is classpath resources)
spring.devtools.restart.additional-paths=src/main/java,src/main/resources

# Enable live reload support (for browser auto-refresh)
spring.devtools.livereload.enabled=true

spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
spring.data.mongodb.database=demo
logging.level.org.springframework.data.mongodb.core=DEBUG